- name: "Install fail2ban"
  apt:
    name: fail2ban

- name: "Install ansible docker requirements"
  apt:
    name: python-setuptools
    state: installed
    update_cache: True
  with_items:
    - dnsutils
    - python-setuptools

- name: "Install python pip"
  easy_install:
    name: pip
    state: latest

- name: "Install docker-py"
  pip:
    name: docker-py

- name: "docker-compose 1.9.0 install"
  pip:
    name: docker-compose
    #use old version to avoid splitdrive issue
    version: 1.9.0

